### ISSUE TITLE
Теряются метода eventEmitter при использовании `Object.mixin`

### ISSUE THREAD

**Issue by shining-mind** [V4Fire/Client#1100]
Пример:

```
< b-dummy :v-attrs = Object.mixin( &
	{deep: true, convertArray: false},
	{random: Math.random()},
	{'v-bind-with': [{on: 'click', emitter: selfEmitter, then: () => console.log('emitted')}]}
) .
```

Будет получена ошибка:

```
ReferenceError: A method to attach events is not defined
    at wrapper (p-v4-components-demo.js:5194:31)
    at Async.registerTask (p-v4-components-demo.js:4778:39)
    at Async.on (p-v4-components-demo.js:5161:31)
    at p-v4-components-demo.js:35760:16
    at Array.forEach (<anonymous>)
    at bindListenerToElement (p-v4-components-demo.js:35734:32)
    at mounted (p-v4-components-demo.js:35826:103)
    at callWithErrorHandling (vue.js:1713:24)
    at callWithAsyncErrorHandling (vue.js:1722:23)
    at invokeDirectiveHook (vue.js:4333:15)
```

`Object.mixin` теряет свойства из emitter, который не помечены как `enumerable`:

https://github.com/V4Fire/Core/blob/2ab18049421b9b78811f1ecae7a3f8f712b8e99b/src/core/async/modules/wrappers/index.ts#L209-L211

**Comment by shining-mind** [comment]
Решение: использовать `Object.mixin` с опцией `withNonEnumerables = true`
